import * as fs from "fs";
import { MetadataLoadContext, MetadataAssemblyResolver, AssemblyName, Assembly } from "System.Reflection";
import assert from "assert";
const s_SimpleNameOnlyImage =
    Uint8Array.from(Buffer.from(
        "TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFt" +
        "IGNhbm5vdCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAABQRQAATAEDAFlyX1sAAAAAAAAAAOAAIiALATAAAAQAAAAGAAAAAAAA8iIAAAAgAAAAQAAA" +
        "AAAAEAAgAAAAAgAABAAAAAAAAAAEAAAAAAAAAACAAAAAAgAAAAAAAAMAQIUAABAAABAAAAAAEAAAEAAAAAAAABAAAAAAAAAAAAAAAKAiAABPAAAAAEAAAMAC" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAGAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAACAAAAAAAAAAAAAAA" +
        "CCAAAEgAAAAAAAAAAAAAAC50ZXh0AAAA+AIAAAAgAAAABAAAAAIAAAAAAAAAAAAAAAAAACAAAGAucnNyYwAAAMACAAAAQAAAAAQAAAAGAAAAAAAAAAAAAAAA" +
        "AABAAABALnJlbG9jAAAMAAAAAGAAAAACAAAACgAAAAAAAAAAAAAAAAAAQAAAQgAAAAAAAAAAAAAAAAAAAADUIgAAAAAAAEgAAAACAAUAUCAAAFACAAABAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEJTSkIBAAEAAAAAAAwAAAB2NC4wLjMwMzE5AAAAAAUAbAAAALQA" +
        "AAAjfgAAIAEAANAAAAAjU3RyaW5ncwAAAADwAQAABAAAACNVUwD0AQAAEAAAACNHVUlEAAAABAIAAEwAAAAjQmxvYgAAAAAAAAACAAABBxQAAAkAAAAA+gEz" +
        "ABYAAAEAAAAEAAAAAQAAAAMAAAADAAAAAQAAAAEAAAAAAGUAAQAAAAAABgAnAJEABgBHAJEABgATAH4ADwCxAAAAAAAAAAEAAAAAAAEAAQAJAHgAAQARAHgA" +
        "BgAZAHgACgAuAAsAGQAuABMAIgAuABsAQQAEgAAAAAAAAAAAAAAAAAAAAADAAAAABAAAAAAAAAAAAAAAEAAKAAAAAAAAAAA8TW9kdWxlPgBtc2NvcmxpYgBE" +
        "ZWJ1Z2dhYmxlQXR0cmlidXRlAENvbXBpbGF0aW9uUmVsYXhhdGlvbnNBdHRyaWJ1dGUAUnVudGltZUNvbXBhdGliaWxpdHlBdHRyaWJ1dGUAU2ltcGxlTmFt" +
        "ZU9ubHkuZGxsAC5jdG9yAFN5c3RlbS5EaWFnbm9zdGljcwBTeXN0ZW0uUnVudGltZS5Db21waWxlclNlcnZpY2VzAERlYnVnZ2luZ01vZGVzAFNpbXBsZU5h" +
        "bWVPbmx5AAAAAAAAlQG8FLXKY0WTP70y4IIRdAAEIAEBCAMgAAEFIAEBEREIt3pcVhk04IkIAQAIAAAAAAAeAQABAFQCFldyYXBOb25FeGNlcHRpb25UaHJv" +
        "d3MBCAEABwEAAAAAAADIIgAAAAAAAAAAAADiIgAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1CIAAAAAAAAAAAAAAABfQ29yRGxsTWFpbgBtc2NvcmVlLmRs" +
        "bAAAAAAA/yUAIAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAABABAAAAAYAACAAAAAAAAAAAAAAAAAAAABAAEAAAAwAACAAAAAAAAAAAAAAAAAAAABAAAAAABIAAAAWEAAAGQCAAAAAAAA" +
        "AAAAAGQCNAAAAFYAUwBfAFYARQBSAFMASQBPAE4AXwBJAE4ARgBPAAAAAAC9BO/+AAABAAAAAAAAAAAAAAAAAAAAAAA/AAAAAAAAAAQAAAACAAAAAAAAAAAA" +
        "AAAAAAAARAAAAAEAVgBhAHIARgBpAGwAZQBJAG4AZgBvAAAAAAAkAAQAAABUAHIAYQBuAHMAbABhAHQAaQBvAG4AAAAAAAAAsATEAQAAAQBTAHQAcgBpAG4A" +
        "ZwBGAGkAbABlAEkAbgBmAG8AAACgAQAAAQAwADAAMAAwADAANABiADAAAAAsAAIAAQBGAGkAbABlAEQAZQBzAGMAcgBpAHAAdABpAG8AbgAAAAAAIAAAADAA" +
        "CAABAEYAaQBsAGUAVgBlAHIAcwBpAG8AbgAAAAAAMAAuADAALgAwAC4AMAAAAEYAEwABAEkAbgB0AGUAcgBuAGEAbABOAGEAbQBlAAAAUwBpAG0AcABsAGUA" +
        "TgBhAG0AZQBPAG4AbAB5AC4AZABsAGwAAAAAACgAAgABAEwAZQBnAGEAbABDAG8AcAB5AHIAaQBnAGgAdAAAACAAAABOABMAAQBPAHIAaQBnAGkAbgBhAGwA" +
        "RgBpAGwAZQBuAGEAbQBlAAAAUwBpAG0AcABsAGUATgBhAG0AZQBPAG4AbAB5AC4AZABsAGwAAAAAADQACAABAFAAcgBvAGQAdQBjAHQAVgBlAHIAcwBpAG8A" +
        "bgAAADAALgAwAC4AMAAuADAAAAA4AAgAAQBBAHMAcwBlAG0AYgBsAHkAIABWAGUAcgBzAGkAbwBuAAAAMAAuADAALgAwAC4AMAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAMAAAA9DIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAA"
        , "base64"));


const s_DerivedClassWithVariationsOnFooImage = Uint8Array.from(Buffer.from(
    "TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFt" +
    "IGNhbm5vdCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAABQRQAATAECAIgKaVsAAAAAAAAAAOAAAiELAQsAAAYAAAACAAAAAAAAriUAAAAgAAAAQAAA" +
    "AAAAEAAgAAAAAgAABAAAAAAAAAAEAAAAAAAAAABgAAAAAgAAAAAAAAMAQIUAABAAABAAAAAAEAAAEAAAAAAAABAAAAAAAAAAAAAAAFQlAABXAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAEAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAACAAAAAAAAAAAAAAA" +
    "CCAAAEgAAAAAAAAAAAAAAC50ZXh0AAAAtAUAAAAgAAAABgAAAAIAAAAAAAAAAAAAAAAAACAAAGAucmVsb2MAAAwAAAAAQAAAAAIAAAAIAAAAAAAAAAAAAAAA" +
    "AABAAABCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQJQAAAAAAAEgAAAACAAUApCAAALAEAAABAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACICKAMAAAoAKiICKAQAAAoAKiICKAUAAAoAKiICKAYAAAoAKiIC" +
    "KAcAAAoAKiICKAgAAAoAKiICKAkAAAoAKiICKAoAAAoAKiICKAsAAAoAKgAAAEJTSkIBAAEAAAAAAAwAAAB2NC4wLjMwMzE5AAAAAAUAbAAAALwCAAAjfgAA" +
    "KAMAACABAAAjU3RyaW5ncwAAAABIBAAACAAAACNVUwBQBAAAEAAAACNHVUlEAAAAYAQAAFAAAAAjQmxvYgAAAAAAAAACAAABRxQAAAkAAAAA+iUzABYAAAEA" +
    "AAALAAAACgAAAAkAAAALAAAAAgAAAAEAAAAKAAAAAACkAAEAAAAAAAYAKgAKAAYAUAAKAAoAbgAAAA4AdAAAABIAegAAABYAgAAAABoAhgAAAB4AjAAAACIA" +
    "kgAAACYAmAAAACoAngAAAAAAAAABAAAAAAABAAEAAQAQAMcAAAANAAEAAQABABAA0AAAABEAAQACAAEAEADZAAAAFQABAAMAAQAQAOIAAAAZAAEABAABABAA" +
    "6wAAAB0AAQAFAAEAEAD0AAAAIQABAAYAAQAQAP0AAAAlAAEABwABABAABgEAACkAAQAIAAEAEAAPAQAALQABAAkAUCAAAAAAhhhKAAYAAQBZIAAAAACGGEoA" +
    "BgABAGIgAAAAAIYYSgAGAAEAayAAAAAAhhhKAAYAAQB0IAAAAACGGEoABgABAH0gAAAAAIYYSgAGAAEAhiAAAAAAhhhKAAYAAQCPIAAAAACGGEoABgABAJgg" +
    "AAAAAIYYSgAGAAEACQBKAAEAEQBKAAYAGQBKAAYAIQBKAAYAKQBKAAYAMQBKAAYAOQBKAAYAQQBKAAYASQBKAAYAUQBKAAYAWQBKAAYALgALACUALgATAC4A" +
    "BIAAAAAAAAAAAAAAAAAAAAAAGAEAAAQAAAAAAAAAAAAAAAoAsAAAAAAAAAAAAAAAAAAAAAAAEwC5AAAAAAAAAAAAAAAAAAAAAAATALkAAAAAAAAAAAAAAAAA" +
    "AAAAABMAvQAAAAAAAAAAAAAAAQAAAAAAEwC5AAAAAAAAAAAAAAAAAAAAAAATALkAwQAAAAAAAAAAAAAAAAAAABwAuQAAAAAAAAAAAAAAAAAAAAAAEwC5AAAA" +
    "AAAAAAAAAAAAAAAAAAATALkAAAAAAAAAAAAAAAAAAAAAABMAuQAAAAAAAAAAPE1vZHVsZT4AU3lzdGVtLlJ1bnRpbWUuQ29tcGlsZXJTZXJ2aWNlcwBDb21w" +
    "aWxhdGlvblJlbGF4YXRpb25zQXR0cmlidXRlAC5jdG9yAFJ1bnRpbWVDb21wYXRpYmlsaXR5QXR0cmlidXRlAEJhc2UxAEJhc2UyAEJhc2UzAEJhc2U0AEJh" +
    "c2U1AEJhc2U2AEJhc2U3AEJhc2U4AEJhc2U5AERlcml2ZWQuZGxsAG1zY29ybGliAEZvbwBHb28AZW4tdXMARGVyaXZlZDEARGVyaXZlZDIARGVyaXZlZDMA" +
    "RGVyaXZlZDQARGVyaXZlZDUARGVyaXZlZDYARGVyaXZlZDcARGVyaXZlZDgARGVyaXZlZDkARGVyaXZlZAAAAyAAAAAAAJ0aH0wAVohAiGLn9KIYpgsABCAB" +
    "AQgDIAABCLd6XFYZNOCJCMysku2HOxhcCN2sku2HOxhcCAEACAAAAAAAHgEAAQBUAhZXcmFwTm9uRXhjZXB0aW9uVGhyb3dzAQAAAHwlAAAAAAAAAAAAAJ4l" +
    "AAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQJQAAAAAAAAAAAAAAAAAAAAAAAAAAX0NvckRsbE1haW4AbXNjb3JlZS5kbGwAAAAAAP8lACAAEAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAADAAAALA1AAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
    , "base64"));

const s_BaseClassesImage = Uint8Array.from(Buffer.from(
    "TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFt" +
    "IGNhbm5vdCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAABQRQAATAEDAE4MaVsAAAAAAAAAAOAAIiALATAAAAYAAAAGAAAAAAAAOiQAAAAgAAAAQAAA" +
    "AAAAEAAgAAAAAgAABAAAAAAAAAAEAAAAAAAAAACAAAAAAgAAAAAAAAMAQIUAABAAABAAAAAAEAAAEAAAAAAAABAAAAAAAAAAAAAAAOgjAABPAAAAAEAAAJgC" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAGAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAACAAAAAAAAAAAAAAA" +
    "CCAAAEgAAAAAAAAAAAAAAC50ZXh0AAAAQAQAAAAgAAAABgAAAAIAAAAAAAAAAAAAAAAAACAAAGAucnNyYwAAAJgCAAAAQAAAAAQAAAAIAAAAAAAAAAAAAAAA" +
    "AABAAABALnJlbG9jAAAMAAAAAGAAAAACAAAADAAAAAAAAAAAAAAAAAAAQAAAQgAAAAAAAAAAAAAAAAAAAAAcJAAAAAAAAEgAAAACAAUAXCAAAIwDAAABAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACICKAQAAAoAKgAAAEJTSkIBAAEAAAAAAAwAAAB2NC4wLjMwMzE5" +
    "AAAAAAUAbAAAAMABAAAjfgAALAIAAAABAAAjU3RyaW5ncwAAAAAsAwAABAAAACNVUwAwAwAAEAAAACNHVUlEAAAAQAMAAEwAAAAjQmxvYgAAAAAAAAACAAAB" +
    "RxQAAAkAAAAA+gEzABYAAAEAAAAFAAAACgAAAAkAAAAEAAAAAwAAAAEAAAABAAAAAACgAAEAAAAAAAYAYgDJAAYAggDJAAYATgC2AA8A6QAAAAYA+ACpAAAA" +
    "AAA3AAAAAAABAAEAAQAQAAEAAAAVAAEAAQABABAABwAAABUAAQACAAEAEAANAAAAFQABAAMAAQAQABMAAAAVAAEABAABABAAGQAAABUAAQAFAAEAEAAfAAAA" +
    "FQABAAYAAQAQACUAAAAVAAEABwABABAAKwAAABUAAQAIAAEAEAAxAAAAFQABAAkAUCAAAAAAhhiwAAYAAQBQIAAAAACGGLAABgABAFAgAAAAAIYYsAAGAAEA" +
    "UCAAAAAAhhiwAAYAAQBQIAAAAACGGLAABgABAFAgAAAAAIYYsAAGAAEAUCAAAAAAhhiwAAYAAQBQIAAAAACGGLAABgABAFAgAAAAAIYYsAAGAAEACQCwAAEA" +
    "EQCwAAYAGQCwAAoAKQCwAAYALgALABkALgATACIALgAbAEEABIAAAAAAAAAAAAAAAAAAAAAASQAAAAQAAAAAAAAAAAAAABAAQAAAAAAAAAAAQmFzZTEAQmFz" +
    "ZTIAQmFzZTMAQmFzZTQAQmFzZTUAQmFzZTYAQmFzZTcAQmFzZTgAQmFzZTkAPE1vZHVsZT4AbXNjb3JsaWIAQmFzZQBEZWJ1Z2dhYmxlQXR0cmlidXRlAENv" +
    "bXBpbGF0aW9uUmVsYXhhdGlvbnNBdHRyaWJ1dGUAUnVudGltZUNvbXBhdGliaWxpdHlBdHRyaWJ1dGUAQmFzZS5kbGwAU3lzdGVtAC5jdG9yAFN5c3RlbS5E" +
    "aWFnbm9zdGljcwBTeXN0ZW0uUnVudGltZS5Db21waWxlclNlcnZpY2VzAERlYnVnZ2luZ01vZGVzAE9iamVjdAAAAAAAANDOsbff9aVMp54uTMWNxRgABCAB" +
    "AQgDIAABBSABARERCLd6XFYZNOCJCAEACAAAAAAAHgEAAQBUAhZXcmFwTm9uRXhjZXB0aW9uVGhyb3dzAQgBAAcBAAAAAAAAECQAAAAAAAAAAAAAKiQAAAAg" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAABwkAAAAAAAAAAAAAAAAX0NvckRsbE1haW4AbXNjb3JlZS5kbGwAAAAAAP8lACAAEAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAEAAAABgA" +
    "AIAAAAAAAAAAAAAAAAAAAAEAAQAAADAAAIAAAAAAAAAAAAAAAAAAAAEAAAAAAEgAAABYQAAAPAIAAAAAAAAAAAAAPAI0AAAAVgBTAF8AVgBFAFIAUwBJAE8A" +
    "TgBfAEkATgBGAE8AAAAAAL0E7/4AAAEAAAAAAAAAAAAAAAAAAAAAAD8AAAAAAAAABAAAAAIAAAAAAAAAAAAAAAAAAABEAAAAAQBWAGEAcgBGAGkAbABlAEkA" +
    "bgBmAG8AAAAAACQABAAAAFQAcgBhAG4AcwBsAGEAdABpAG8AbgAAAAAAAACwBJwBAAABAFMAdAByAGkAbgBnAEYAaQBsAGUASQBuAGYAbwAAAHgBAAABADAA" +
    "MAAwADAAMAA0AGIAMAAAACwAAgABAEYAaQBsAGUARABlAHMAYwByAGkAcAB0AGkAbwBuAAAAAAAgAAAAMAAIAAEARgBpAGwAZQBWAGUAcgBzAGkAbwBuAAAA" +
    "AAAwAC4AMAAuADAALgAwAAAAMgAJAAEASQBuAHQAZQByAG4AYQBsAE4AYQBtAGUAAABCAGEAcwBlAC4AZABsAGwAAAAAACgAAgABAEwAZQBnAGEAbABDAG8A" +
    "cAB5AHIAaQBnAGgAdAAAACAAAAA6AAkAAQBPAHIAaQBnAGkAbgBhAGwARgBpAGwAZQBuAGEAbQBlAAAAQgBhAHMAZQAuAGQAbABsAAAAAAA0AAgAAQBQAHIA" +
    "bwBkAHUAYwB0AFYAZQByAHMAaQBvAG4AAAAwAC4AMAAuADAALgAwAAAAOAAIAAEAQQBzAHMAZQBtAGIAbAB5ACAAVgBlAHIAcwBpAG8AbgAAADAALgAwAC4A" +
    "MAAuADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAACAAAAwAAAA8NAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
    , "base64"));



class EmptyCoreMetadataAssemblyResolver implements MetadataAssemblyResolver {
    public constructor() { }

    public Resolve(context: MetadataLoadContext, assemblyName: AssemblyName): Assembly | undefined {
        if (assemblyName.Name == "mscorlib") {
            if (this._coreAssembly == undefined) {
                // This assembly has no types, so any access to core types will throw
                this._coreAssembly = context.LoadFromByteArray(s_SimpleNameOnlyImage);
            }

            return this._coreAssembly;
        }

        return undefined;
    }

    private _coreAssembly?: Assembly;
}

class ResolverReturnsSomething implements MetadataAssemblyResolver {
    public constructor() {}

    public Resolve(context: MetadataLoadContext, assemblyName: AssemblyName): Assembly | undefined {
        this.Context = context;
        this.AssemblyName = assemblyName;
        this.CallCount++;

        this.Assembly = context.LoadFromByteArray(s_BaseClassesImage);
        return this.Assembly;
    }

    public Assembly!: Assembly;
    public AssemblyName!: AssemblyName;
    public Context!: MetadataLoadContext;
    public CallCount!: number;
}

export function LoadBinary() {
    const buf = fs.readFileSync("samples/test.dll");
    const lc = new MetadataLoadContext(new EmptyCoreMetadataAssemblyResolver());
    const a = lc.LoadFromByteArray(Uint8Array.from(buf));
    assert(a != undefined);
}

export function ResolverReturns() {
    var resolver = new ResolverReturnsSomething();
    const lc = new MetadataLoadContext(resolver);

    assert(lc == resolver.Context);
    assert(1 == resolver.CallCount);

    const derived = lc.LoadFromByteArray(s_DerivedClassWithVariationsOnFooImage);
    const t = derived.GetType("Derived1", true);
    const bt = t?.BaseType;

    // Assert.Same(lc, resolver.Context);
    assert("Foo" == resolver.AssemblyName.Name);
    // Assert.Equal(2, resolver.CallCount);

    // Assembly a = bt.Assembly;
    // Assert.Equal(a, resolver.Assembly);

}