export enum MetadataKind {
    /// <summary>
    /// CLI metadata.
    /// </summary>
    Ecma335 = 0,

    /// <summary>
    /// Windows Metadata.
    /// </summary>
    WindowsMetadata = 1,

    /// <summary>
    /// Windows Metadata generated by managed compilers.
    /// </summary>
    ManagedWindowsMetadata = 2,
}